<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CountriesSeeder extends Seeder
{
    public function run()
    {
        $countries = [
            ['country' => 'Andorra', 'status' => 'active'],
            ['country' => 'Angola', 'status' => 'active'],
            ['country' => 'Antigua and Barbuda', 'status' => 'active'],
            ['country' => 'Argentina', 'status' => 'active'],
            ['country' => 'Australia', 'status' => 'active'],
            ['country' => 'Azerbaijan', 'status' => 'active'],
            ['country' => 'Bahamas', 'status' => 'active'],
            ['country' => 'Bahrain', 'status' => 'active'],
            ['country' => 'Barbados', 'status' => 'active'],
            ['country' => 'Belarus', 'status' => 'active'],
            ['country' => 'Belgium', 'status' => 'active'],
            ['country' => 'Belize', 'status' => 'active'],
            ['country' => 'Bhutan', 'status' => 'active'],
            ['country' => 'Bolivia', 'status' => 'active'],
            ['country' => 'Bosnia and Herzegovina', 'status' => 'active'],
            ['country' => 'Brazil', 'status' => 'active'],
            ['country' => 'Brunei', 'status' => 'active'],
            ['country' => 'Bulgaria', 'status' => 'active'],
            ['country' => 'Burkina Faso', 'status' => 'active'],
            ['country' => 'Burundi', 'status' => 'active'],
            ['country' => 'Cambodia', 'status' => 'active'],
            ['country' => 'Cameroon', 'status' => 'active'],
            ['country' => 'Cape Verde', 'status' => 'active'],
            ['country' => 'Central African Republic', 'status' => 'active'],
            ['country' => 'Chad', 'status' => 'active'],
            ['country' => 'Chile', 'status' => 'active'],
            ['country' => 'China', 'status' => 'active'],
            ['country' => 'Colombia', 'status' => 'active'],
            ['country' => 'Comoros', 'status' => 'active'],
            ['country' => 'Congo', 'status' => 'active'],
            ['country' => 'Costa Rica', 'status' => 'active'],
            ['country' => 'Croatia', 'status' => 'active'],
            ['country' => 'Cuba', 'status' => 'active'],
            ['country' => 'Cyprus', 'status' => 'active'],
            ['country' => 'Czech Republic', 'status' => 'active'],
            ['country' => 'Denmark', 'status' => 'active'],
            ['country' => 'Djibouti', 'status' => 'active'],
            ['country' => 'Dominica', 'status' => 'active'],
            ['country' => 'Dominican Republic', 'status' => 'active'],
            ['country' => 'Ecuador', 'status' => 'active'],
            ['country' => 'El Salvador', 'status' => 'active'],
            ['country' => 'Equatorial Guinea', 'status' => 'active'],
            ['country' => 'Eritrea', 'status' => 'active'],
            ['country' => 'Estonia', 'status' => 'active'],
            ['country' => 'Eswatini', 'status' => 'active'],
            ['country' => 'Fiji', 'status' => 'active'],
            ['country' => 'Finland', 'status' => 'active'],
            ['country' => 'Gabon', 'status' => 'active'],
            ['country' => 'Gambia', 'status' => 'active'],
            ['country' => 'Grenada', 'status' => 'active'],
            ['country' => 'Guatemala', 'status' => 'active'],
            ['country' => 'Guinea', 'status' => 'active'],
            ['country' => 'Guinea-Bissau', 'status' => 'active'],
            ['country' => 'Guyana', 'status' => 'active'],
            ['country' => 'Haiti', 'status' => 'active'],
            ['country' => 'Honduras', 'status' => 'active'],
            ['country' => 'Hungary', 'status' => 'active'],
            ['country' => 'Iceland', 'status' => 'active'],
            ['country' => 'Iran', 'status' => 'active'],
            ['country' => 'Ireland', 'status' => 'active'],
            ['country' => 'Israel', 'status' => 'active'],
            ['country' => 'Jamaica', 'status' => 'active'],
            ['country' => 'Japan', 'status' => 'active'],
            ['country' => 'Jordan', 'status' => 'active'],
            ['country' => 'Kazakhstan', 'status' => 'active'],
            ['country' => 'Kiribati', 'status' => 'active'],
            ['country' => 'Kyrgyzstan', 'status' => 'active'],
            ['country' => 'Laos', 'status' => 'active'],
            ['country' => 'Latvia', 'status' => 'active'],
            ['country' => 'Lebanon', 'status' => 'active'],
            ['country' => 'Lesotho', 'status' => 'active'],
            ['country' => 'Liberia', 'status' => 'active'],
            ['country' => 'Libya', 'status' => 'active'],
            ['country' => 'Liechtenstein', 'status' => 'active'],
            ['country' => 'Lithuania', 'status' => 'active'],
            ['country' => 'Luxembourg', 'status' => 'active'],
            ['country' => 'Madagascar', 'status' => 'active'],
            ['country' => 'Malawi', 'status' => 'active'],
            ['country' => 'Malaysia', 'status' => 'active'],
            ['country' => 'Mali', 'status' => 'active'],
            ['country' => 'Malta', 'status' => 'active'],
            ['country' => 'Marshall Islands', 'status' => 'active'],
            ['country' => 'Mauritania', 'status' => 'active'],
            ['country' => 'Mauritius', 'status' => 'active'],
            ['country' => 'Mexico', 'status' => 'active'],
            ['country' => 'Micronesia', 'status' => 'active'],
            ['country' => 'Moldova', 'status' => 'active'],
            ['country' => 'Monaco', 'status' => 'active'],
            ['country' => 'Mongolia', 'status' => 'active'],
            ['country' => 'Mozambique', 'status' => 'active'],
            ['country' => 'Myanmar', 'status' => 'active'],
            ['country' => 'Namibia', 'status' => 'active'],
            ['country' => 'Nauru', 'status' => 'active'],
            ['country' => 'Nicaragua', 'status' => 'active'],
            ['country' => 'Niger', 'status' => 'active'],
            ['country' => 'North Macedonia', 'status' => 'active'],
            ['country' => 'Norway', 'status' => 'active'],
            ['country' => 'Palau', 'status' => 'active'],
            ['country' => 'Panama', 'status' => 'active'],
            ['country' => 'Paraguay', 'status' => 'active'],
            ['country' => 'Peru', 'status' => 'active'],
            ['country' => 'Poland', 'status' => 'active'],
            ['country' => 'Portugal', 'status' => 'active'],
            ['country' => 'Russia', 'status' => 'active'],
            ['country' => 'Saint Kitts and Nevis', 'status' => 'active'],
            ['country' => 'Saint Lucia', 'status' => 'active'],
            ['country' => 'Saint Vincent and the Grenadines', 'status' => 'active'],
            ['country' => 'Samoa', 'status' => 'active'],
            ['country' => 'San Marino', 'status' => 'active'],
            ['country' => 'Sao Tome and Principe', 'status' => 'active'],
            ['country' => 'Senegal', 'status' => 'active'],
            ['country' => 'Serbia', 'status' => 'active'],
            ['country' => 'Seychelles', 'status' => 'active'],
            ['country' => 'Sierra Leone', 'status' => 'active'],
            ['country' => 'Singapore', 'status' => 'active'],
            ['country' => 'Slovakia', 'status' => 'active'],
            ['country' => 'Slovenia', 'status' => 'active'],
            ['country' => 'Solomon Islands', 'status' => 'active'],
            ['country' => 'Suriname', 'status' => 'active'],
            ['country' => 'Sweden', 'status' => 'active'],
            ['country' => 'Taiwan', 'status' => 'active'],
            ['country' => 'Thailand', 'status' => 'active'],
            ['country' => 'Timor-Leste', 'status' => 'active'],
            ['country' => 'Tonga', 'status' => 'active'],
            ['country' => 'Trinidad and Tobago', 'status' => 'active'],
            ['country' => 'Turkmenistan', 'status' => 'active'],
            ['country' => 'Tuvalu', 'status' => 'active'],
            ['country' => 'Uruguay', 'status' => 'active'],
            ['country' => 'Uzbekistan', 'status' => 'active'],
            ['country' => 'Vanuatu', 'status' => 'active'],
            ['country' => 'Venezuela', 'status' => 'active'],
            ['country' => 'Vietnam', 'status' => 'active'],
            ['country' => 'Zambia', 'status' => 'active']
        ];

        // Insert countries into the database
        foreach ($countries as $country) {
            DB::table('countries')->insert([
                'country' => $country['country'],
                'status' => $country['status'],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ]);
        }
    }
}
